<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contoh Modularisasi</title>
    <link rel="stylesheet" href="style.css" type ="text/stylesheet" media = "screen" />
</head>
<body>
    <div class= "container">
        <header>
            <h1>Modularisasi Menggunakan Require </h1>
        </header>
        <nav>
            <a href="HOME.php"> Home</a>
            <a href="ABOUT.php">About</a>
            <a href="Lab8Web/index.php"> Kontak</a>
        </nav>
        
    </div>
</body>
</html>